### PR TITLE
Fix validation of ingredients with decimal quantities

### LINKED ISSUE #6: Fractions not being recognized properly as quantities
Via feedback form:

> https://www.allrecipes.com/recipe/57028/amazingly-good-eggnog/
>
> ½ gets displayed as 5 and not as part of the highlighted quantity value. Ideally, it would be recognized as part of the quantity and the ½ character would be used directly, but if there are font problems with that then perhaps convert to 1/2. I suspect the same issue will occur with ¼ and ¾ as well.

### PR DESCRIPTION
**Pull request by emdash**
This is based on PR #7.

Validation of recipe quantities now decimal quantities like `.y` and `x.y`.

Testing Done:
- npm run lint
- npm run test
- manual testing: https://www.allrecipes.com/recipe/76778/slow-cook-thai-chicken/ now shows `0.666... cups of creamy penut butter`, where before it was parsing incorrectly and rendering as `0 66666668653488 cup creamy penut butter`. 
- manual testing: https://www.allrecipes.com/recipe/57028/amazingly-good-eggnog/
- manual testing: https://cooking.nytimes.com/recipes/1016196-coconut-red-curry-with-tofu (recipe ingredient with missing unit).

Fixes #6

### CODE REVIEW

File: src/js/sanitize.js [hunk 1]
```diff
@@ -152,9 +152,9 @@ const FRACTIONS = Object.values(FRACT_MAP).join('');
 // Try to match things like "1 tablespoon sugar"
 const RECIPE_QUANTITY_RE = new RegExp([
   '^',
-  `((?:\\d+\\s?)?[\\d${FRACTIONS}⁄-]+)`,
+  `((?:\\.\\d+|\\d+(?:\\.\\d+)?)?(?:\\s*[${FRACTIONS}-])?(?:\\s*⁄\\d+)?)`,
   '\\s*',
-  `(${QUANTITIES.join('|')})?\\.?`,
```
Comment (erik) [inline src/js/sanitize.js:157]: Is removing the trailing dot intentional here? iirc it was to handle the occasional trailing punctuation on certain units (`tsp.`, `oz.`)

File: src/js/sanitize.js [hunk 2]
```diff
@@ -152,9 +152,9 @@ const FRACTIONS = Object.values(FRACT_MAP).join('');
 // Try to match things like "1 tablespoon sugar"
 const RECIPE_QUANTITY_RE = new RegExp([
   '^',
-  `((?:\\d+\\s?)?[\\d${FRACTIONS}⁄-]+)`,
+  `((?:\\.\\d+|\\d+(?:\\.\\d+)?)?(?:\\s*[${FRACTIONS}-])?(?:\\s*⁄\\d+)?)`,
```
Comment (erik) [inline src/js/sanitize.js:155]: Can split decimals and fractions to separate regexes here to make it slightly more readable. Although with how many edge cases have been added over the years I wouldn't be surprised if someone on the internet used `.5 ¼ cloves`

File: src/js/sanitize.js [hunk 3]
```diff
@@ -163,11 +163,17 @@ const RECIPE_QUANTITY_RE = new RegExp([
 function sanitizeIngredient (ingredient) {
   const match = ingredient.match(RECIPE_QUANTITY_RE);
 
-  if (match === null) {
-    return {ingredient};
+  // only set properties for the capture groups which ended up matching.
```
Comment (erik) [inline src/js/sanitize.js:166]: Does this change anything downstream compared to having them set to `null`?

**Review by erik — COMMENTED** [review]
Thanks for the fix!

Doesn't have to be part of this change, but I'm thinking a nice future addition would be to convert common decimals back to fraction characters e.g. `0.6666... -> ⅔`

File: src/js/sanitize.js (hunk 2 above)
Comment (emdash) [reply src/js/sanitize.js:155]: I always start with the least-invasive / most minimal approach that passes all the existing tests. Having said that, regexes are a write-only medium. The subsequent code assumes 3 capture groups, and I was trying to preserve that. All this code lives within the *quantity* capture group.

Within this, there's three non-capturing groups in sequence, but each non-capturing group is essentially optional, and independent. Any subset of them can match, and you'll get a match object back.

The first group handles numbers of the following forms: `.y` `x`, `x.y` where `x` and `y` are arbitrary sequences of at least one digit.

The second group handles fractions. The the third group was intended to deal with trailing numbers. I think this might be a comment on an older version of the code, because I thought I handled the quote character in that sub-pattern.

File: src/js/sanitize.js (hunk 1 above)
Comment (emdash) [reply src/js/sanitize.js:157]: Probably not. I guess I should fix that, and add a test case for this form.

File: src/js/sanitize.js (hunk 3 above)
Comment (emdash) [reply src/js/sanitize.js:166]: It is really hard to know because javascript. JavaScript gives you ways to treat various values as "truthy" or "falsey", and it also gives you ways to explicitly distinguish between `false`, `null`, *empty string*, *empty array*, `x: undefined`, and *x is not present in y*. I generally prefer `if (x) ...` to `if (x === null)` for this exact reason, but occasionally the distinction matters. Are you doing anything crazy elsewhere where the difference would matter?

The only code that *should* explicitly about the above distinction is the test framework, and rightfully so. I've made adjustments to a couple test cases.

This way of doing it resulted only one test case needing to be changed, vs several of them.

**Comment by emdash** [comment]
> Thanks for the fix!
> 
> Doesn't have to be part of this change, but I'm thinking a nice future addition would be to convert common decimals back to fraction characters e.g. `0.6666... -> ⅔`

I get what you mean, but this seems tricky and potentially quite brittle.

I was suprised that recipe json uses decimal quantities for customary units, when the article text uses unicode fractions.

I think there needs to be a sidebar for managing and editing recipes, and then autoconverting fractions would be a useful tool in that toolbox.

I noticed that there's two methods of detecting recipes in a page, and being able to explicitly choose which one would be nice. Sometimes I'd want to preserve the original units, other times I'd prefer the decimalized version.

File: src/js/sanitize.js (hunk 3 above)
Comment (erik) [reply src/js/sanitize.js:166]: > Are you doing anything crazy

probably, I use javascript only begrudgingly. 

It should be easy enough to confirm, it's a small project. As long as the recipe view continues to render when these values are `undefined` instead of `null` this should be fine

Comment (emdash) [reply src/js/sanitize.js:166]: From what I've seen, though I didn't explicitly look for misbehavior in this case so it's possible I missed it. So I guess I should add that to my manual testing.

**Comment by erik** [comment]
> I get what you mean, but this seems tricky and potentially quite brittle.

What are your concerns? My thought was something pretty dumb:

```javascript
const fractionStr = [[1/3, '1/3'], [1/2, '1/2'], ...]
   .find(([x, c]) => Math.abs(decimalValue - x) < 0.01)?.[1]
```

File: src/js/sanitize.js (hunk 2 above)
Comment (emdash) [reply src/js/sanitize.js:155]: I see what you're saying. This is potentially too permissive. You may be right.

And what you're really suggesting is to change the nesting of the capture groups so, in pseudo-bnf:

   quantity => Integer? ( '.' Integer | '\'' Integer | Fraction)? 

Vs what I have

   quantity => (('.' Integer) | Integer ('.' Integer))?(Fraction)?(Quote)?`

You might be right. I guess it depends what you want. I am biased toward permissiveness here, but I could see it the other way around also.

Comment (erik) [reply src/js/sanitize.js:155]: Honestly permissiveness is generally good here, internet recipes are an endless stream of edge cases. The original regex also allows some invalid sequences anyway. My preference was mainly that the change hit some inflection point in complexity where I don't think I would make sense of the regex next time I see it.

**Comment by emdash** [comment]
> > I get what you mean, but this seems tricky and potentially quite brittle.
> 
> What are your concerns? My thought was something pretty dumb:
> 
> ```js
> const fractionStr = [[1/3, '1/3'], [1/2, '1/2'], ...]
>    .find(([x, c]) => Math.abs(decimalValue - x) < 0.01)?.[1]
> ```

That will probably work. I just would not want to assume that you always want to do this on a given ingredient. For some recipes, sure it's close enough. But molecular gastronomy is also a thing, and I would imagine sometimes you actually do need scientific precision.

And basically this is just the sortof hack that has come to bite me more than once over the years.

File: src/js/sanitize.js (hunk 2 above)
Comment (emdash) [reply src/js/sanitize.js:155]: Well yeah, regexes are notorious, and what's worse you can't include inline comments.

I think I'll leave this one as-is, and could see doing a more in-depth refactoring of this code into something more akin to a recursive-descent parser. This would allow breaking this up into smaller, more comprehensible units. And could support alternative forms like `Ingredient: Quantity Unit`, etc.

But I think I would need to add a lot more test cases. Frankly I'm impressed it works as well as it does.

Comment (emdash) [reply src/js/sanitize.js:155]: I thought about it some more, and I think within one regex it has to be this way, in order to handle the leading decimal point. The first example is equivalent to the original regex.

**Review by erik — APPROVED** [review]
lgtm, thanks!

I'll push a release with your changes when I have a chance later this week
